language: objective-c
osx_image: xcode7.3
before_install:
  - pod repo update
before_script:
  - ./script/disable_sparkle.sh
script:
  - xcodebuild -workspace Hakumai.xcworkspace -scheme Hakumai -configuration Debug -destination 'platform=OS X' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
